# https://taskfile.dev
---
version: "3"

dotenv: ["./.env.test"]

includes:
  hangouts:
    taskfile: ./hangouts/Taskfile.yml
    dir: ./hangouts
  ios:
    taskfile: ./ios/Taskfile.yml
    dir: ./ios
tasks:
  build-hangouts-docker:
    summary: Run hangouts db and server in docker.
    cmds:
      - docker compose down
      - docker rmi -f hangouts-backend:latest
      - docker compose up
  build-hangouts-prod:
    summary: Run Hangouts on the production DB.
    dotenv: ["./.env.production.local"]
    cmds:
      - docker compose down
      - docker rmi -f hangouts-backend:latest
      - docker compose up backend
  sync-openapi:
    summary: Sync swift client and go server with openapi
    cmds:
      - bun run api-docs/index.ts
      - task hangouts:generate
      - task ios:bind-xcode-build
      - task ios:xcode-clean
