# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  generate-api:
    cmds:
      - echo "Building api documentation and re-generating server and client code..."
      - ./scripts/openapi_generate.sh
