# https://taskfile.dev
---
version: "3"

dotenv: ["./.env.test"]

includes:
  hangouts:
    taskfile: ./hangouts/Taskfile.yml
    dir: ./hangouts
tasks:
  build-hangouts-docker:
    summary: Run hangouts db and server in docker.
    cmds:
      - docker compose down
      - docker rmi -f hangouts-backend:latest
      - docker compose up
  build-hangouts-prod:
    summary: Run Hangouts on the production DB.
    dotenv: ["./.env.production.local"]
    cmds:
      - docker compose down
      - docker rmi -f hangouts-backend:latest
      - docker compose up backend
