name: Hangouts.ai
options:
  bundleIdPrefix: com.hangouts
  deploymentTarget:
    iOS: "15.0"

packages:
  SwiftOpenAPIGenerator:
    url: https://github.com/apple/swift-openapi-generator
    from: 1.0.0
  SwiftOpenAPIRuntime:
    url: https://github.com/apple/swift-openapi-runtime
    from: 1.0.0
  SwiftOpenAPIURLSession:
    url: https://github.com/apple/swift-openapi-urlsession
    from: 1.0.0

targets:
  Hangouts:
    type: application
    platform: iOS
    sources:
      - Sources/Hangouts
    dependencies:
      # Link these runtime libraries to your target
      - package: SwiftOpenAPIRuntime
        product: OpenAPIRuntime
      - package: SwiftOpenAPIURLSession
        product: OpenAPIURLSession
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hangouts.ai
        # Remove or update DEVELOPMENT_TEAM if you have one
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    # This is crucial - the build plugin
    buildToolPlugins:
      - package: SwiftOpenAPIGenerator
        plugin: OpenAPIGenerator
