// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1UserPostOperation  OperationName = "APIV1UserPost"
	GetOperation            OperationName = "Get"
	HealthcheckGetOperation OperationName = "HealthcheckGet"
)
