// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1UserPost implements POST /api/v1/user operation.
//
// POST /api/v1/user
func (UnimplementedHandler) APIV1UserPost(ctx context.Context, req OptAPIV1UserPostReq) (r APIV1UserPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Get implements GET / operation.
//
// API documentation.
//
// GET /
func (UnimplementedHandler) Get(ctx context.Context) (r GetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthcheckGet implements GET /healthcheck operation.
//
// GET /healthcheck
func (UnimplementedHandler) HealthcheckGet(ctx context.Context) (r *HealthcheckGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrRespStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrRespStatusCode) {
	r = new(ErrRespStatusCode)
	return r
}
