---
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: hangouts 
      POSTGRES_USER: ${DB_USER:?database username not specified}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?database password not specified}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      dockerfile: dockerfile
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${DB_USER:?database username not specified}
      DB_PASSWORD: ${DB_PASSWORD:?database password not specified}
      DB_NAME: hangouts-api
    ports:
      - ${PORT:-8080}:${PORT:-8081}
volumes:
  postgres-data:
...
