---
version: "3"

tasks:
  run:
    deps:
      - build
    summary: Runs the backend server
    cmds:
      - ./main_server
  build:
    deps:
      - generate
    summary: Build backend executables
    sources:
      - ./**/*.go
    generates:
      - server
    cmds:
      - go mod download
      - go build -o main_server ./main.go
  generate:
    aliases:
      - gen
    summary: Generate server code from OpenAPI spec
    sources:
      - ../openapi.yaml
    generates:
      - gen/
    cmds:
      - bun run ../api-docs/index.ts
      - go generate ./...
  test:
    summary: Run all tests
    deps:
      - build
    cmds:
      - go test -v ./...
  format:
    aliases:
      - fmt
    summary: Format Go code and organize imports
    sources:
      - ./**/*.go
    cmds:
      - $(go env GOPATH)/bin/goimports -w .
      - go mod tidy
  clean:
    summary: Delete build files
    cmds:
      - rm -f main
